### ISSUE TITLE
Just for validation?

### ISSUE THREAD

**Issue by peteruithoven** [jeromeetienne/jsdoced.js#7]
I might not get the idea, but would you recommend adding it to a gulp / grunt workflow, just to add extra validation. Or would you recommend actually distributing the outputted better.js?

**Comment by jeromeetienne** [comment]
i would recommend to add it inside the test procedure yes. maybe the developpers can run it while they develop. but i would advice against using that in production.

the produced code may be used in production but all those checks done by jsdoced.js are consuming resources. this is undesirable in most case.

Does this answer your question ?

**Comment by peteruithoven** [comment]
yes it does, thanks!
