### ISSUE TITLE
privatizeClasses add the "private" option instead of "privatize"

### ISSUE THREAD

**Issue by Gastonite** [jeromeetienne/jsdoced.js#8]
the _privatizeClasses_ argument does not seem to work as expected, it add the private cmdOption, which does not work on Classes.

i tried to replace **private** by **privatize** in the [libs/jsdocExpression.js](https://github.com/Gastonite/jsdoced.js/commit/0f6a3a4d17e78045279615a5a71717bbf7a00df3) file, and it work.

**Comment by jeromeetienne** [comment]
good catch! thanks

**Comment by jeromeetienne** [comment]
thanks for the late action. super nbusy :(
