### ISSUE TITLE
No grunt / gulp task?

### ISSUE THREAD

**Issue by fabm22** [jeromeetienne/jsdoced.js#9]
Hi there, 

Must we rely on grunt exec tasks to directly call "npm jsdoced" without further feedback usable in our automation workflows ?

**Comment by jeromeetienne** [comment]
i am not sure i understand your question. 

the repo doesnt include any grunt or glup task specific to jsdoced. 

it is easy to include the usual jsdoced command line tool in grunt/gulp or any other build system you may use.

btw if you ever build any, i would be glad to include it in the repo
